// Copyright (c) Meta Platforms, Inc. and affiliates.
// Material values: Copyright The Android Open Source Project and Google LLC, Apache-2.0.

/**
 * @file material3Foundation.generated.ts
 * @input Canonical @astryxdesign/material3 web-compat roles
 * @output Self-contained light and dark values for the Core compatibility theme
 * @position Generated theme source copied into the public CLI template
 *
 * Run pnpm -F @astryxdesign/theme-material3 generate:foundation after
 * changing native values; the theme build rejects a stale snapshot.
 */

export const material3WebCompatLight = {
  '--md-sys-color-background': '#fef7ff',
  '--md-sys-color-error': '#b3261e',
  '--md-sys-color-error-container': '#f9dedc',
  '--md-sys-color-inverse-on-surface': '#f5eff7',
  '--md-sys-color-inverse-primary': '#d0bcff',
  '--md-sys-color-inverse-surface': '#322f35',
  '--md-sys-color-on-background': '#1d1b20',
  '--md-sys-color-on-error': '#fff',
  '--md-sys-color-on-error-container': '#410e0b',
  '--md-sys-color-on-primary': '#fff',
  '--md-sys-color-on-primary-container': '#21005d',
  '--md-sys-color-on-primary-fixed': '#21005d',
  '--md-sys-color-on-primary-fixed-variant': '#4f378b',
  '--md-sys-color-on-secondary': '#fff',
  '--md-sys-color-on-secondary-container': '#1d192b',
  '--md-sys-color-on-secondary-fixed': '#1d192b',
  '--md-sys-color-on-secondary-fixed-variant': '#4a4458',
  '--md-sys-color-on-surface': '#1d1b20',
  '--md-sys-color-on-surface-variant': '#49454f',
  '--md-sys-color-on-tertiary': '#fff',
  '--md-sys-color-on-tertiary-container': '#31111d',
  '--md-sys-color-on-tertiary-fixed': '#31111d',
  '--md-sys-color-on-tertiary-fixed-variant': '#633b48',
  '--md-sys-color-outline': '#79747e',
  '--md-sys-color-outline-variant': '#cac4d0',
  '--md-sys-color-primary': '#6750a4',
  '--md-sys-color-primary-container': '#eaddff',
  '--md-sys-color-primary-fixed': '#eaddff',
  '--md-sys-color-primary-fixed-dim': '#d0bcff',
  '--md-sys-color-scrim': '#000',
  '--md-sys-color-secondary': '#625b71',
  '--md-sys-color-secondary-container': '#e8def8',
  '--md-sys-color-secondary-fixed': '#e8def8',
  '--md-sys-color-secondary-fixed-dim': '#ccc2dc',
  '--md-sys-color-shadow': '#000',
  '--md-sys-color-surface': '#fef7ff',
  '--md-sys-color-surface-bright': '#fef7ff',
  '--md-sys-color-surface-container': '#f3edf7',
  '--md-sys-color-surface-container-high': '#ece6f0',
  '--md-sys-color-surface-container-highest': '#e6e0e9',
  '--md-sys-color-surface-container-low': '#f7f2fa',
  '--md-sys-color-surface-container-lowest': '#fff',
  '--md-sys-color-surface-dim': '#ded8e1',
  '--md-sys-color-surface-tint': '#6750a4',
  '--md-sys-color-surface-variant': '#e7e0ec',
  '--md-sys-color-tertiary': '#7d5260',
  '--md-sys-color-tertiary-container': '#ffd8e4',
  '--md-sys-color-tertiary-fixed': '#ffd8e4',
  '--md-sys-color-tertiary-fixed-dim': '#efb8c8',
  '--md-ref-typeface-brand': 'Roboto',
  '--md-ref-typeface-plain': 'Roboto',
  '--md-ref-typeface-weight-bold': '700',
  '--md-ref-typeface-weight-medium': '500',
  '--md-ref-typeface-weight-regular': '400',
  '--md-sys-typescale-display-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-large-line-height': '4rem',
  '--md-sys-typescale-display-large-size': '3.5625rem',
  '--md-sys-typescale-display-large-weight': '400',
  '--md-sys-typescale-display-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-medium-line-height': '3.25rem',
  '--md-sys-typescale-display-medium-size': '2.8125rem',
  '--md-sys-typescale-display-medium-weight': '400',
  '--md-sys-typescale-display-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-small-line-height': '2.75rem',
  '--md-sys-typescale-display-small-size': '2.25rem',
  '--md-sys-typescale-display-small-weight': '400',
  '--md-sys-typescale-headline-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-large-line-height': '2.5rem',
  '--md-sys-typescale-headline-large-size': '2rem',
  '--md-sys-typescale-headline-large-weight': '400',
  '--md-sys-typescale-headline-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-medium-line-height': '2.25rem',
  '--md-sys-typescale-headline-medium-size': '1.75rem',
  '--md-sys-typescale-headline-medium-weight': '400',
  '--md-sys-typescale-headline-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-small-line-height': '2rem',
  '--md-sys-typescale-headline-small-size': '1.5rem',
  '--md-sys-typescale-headline-small-weight': '400',
  '--md-sys-typescale-title-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-large-line-height': '1.75rem',
  '--md-sys-typescale-title-large-size': '1.375rem',
  '--md-sys-typescale-title-large-weight': '400',
  '--md-sys-typescale-title-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-medium-line-height': '1.5rem',
  '--md-sys-typescale-title-medium-size': '1rem',
  '--md-sys-typescale-title-medium-weight': '500',
  '--md-sys-typescale-title-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-small-line-height': '1.25rem',
  '--md-sys-typescale-title-small-size': '0.875rem',
  '--md-sys-typescale-title-small-weight': '500',
  '--md-sys-typescale-body-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-large-line-height': '1.5rem',
  '--md-sys-typescale-body-large-size': '1rem',
  '--md-sys-typescale-body-large-weight': '400',
  '--md-sys-typescale-body-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-medium-line-height': '1.25rem',
  '--md-sys-typescale-body-medium-size': '0.875rem',
  '--md-sys-typescale-body-medium-weight': '400',
  '--md-sys-typescale-body-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-small-line-height': '1rem',
  '--md-sys-typescale-body-small-size': '0.75rem',
  '--md-sys-typescale-body-small-weight': '400',
  '--md-sys-typescale-label-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-large-line-height': '1.25rem',
  '--md-sys-typescale-label-large-size': '0.875rem',
  '--md-sys-typescale-label-large-weight': '500',
  '--md-sys-typescale-label-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-medium-line-height': '1rem',
  '--md-sys-typescale-label-medium-size': '0.75rem',
  '--md-sys-typescale-label-medium-weight': '500',
  '--md-sys-typescale-label-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-small-line-height': '1rem',
  '--md-sys-typescale-label-small-size': '0.6875rem',
  '--md-sys-typescale-label-small-weight': '500',
  '--md-sys-typescale-label-large-weight-prominent': '700',
  '--md-sys-typescale-label-medium-weight-prominent': '700',
  '--md-sys-shape-corner-extra-large': '28px',
  '--md-sys-shape-corner-extra-small': '4px',
  '--md-sys-shape-corner-full': '9999px',
  '--md-sys-shape-corner-large': '16px',
  '--md-sys-shape-corner-medium': '12px',
  '--md-sys-shape-corner-none': '0px',
  '--md-sys-shape-corner-small': '8px',
  '--md-divider-color': 'var(--md-sys-color-outline-variant)',
  '--md-divider-thickness': '1px',
  '--md-badge-color': 'var(--md-sys-color-error)',
  '--md-badge-large-color': 'var(--md-sys-color-error)',
  '--md-badge-large-label-text-color': 'var(--md-sys-color-on-error)',
  '--md-badge-large-label-text-font':
    'var(--md-sys-typescale-label-small-font)',
  '--md-badge-large-label-text-line-height':
    'var(--md-sys-typescale-label-small-line-height)',
  '--md-badge-large-label-text-size':
    'var(--md-sys-typescale-label-small-size)',
  '--md-badge-large-label-text-weight':
    'var(--md-sys-typescale-label-small-weight)',
  '--md-badge-large-shape': 'var(--md-sys-shape-corner-full)',
  '--md-badge-large-size': '16px',
  '--md-badge-shape': 'var(--md-sys-shape-corner-full)',
  '--md-badge-size': '6px',
} as const;

export const material3WebCompatDark = {
  '--md-sys-color-background': '#141218',
  '--md-sys-color-error': '#f2b8b5',
  '--md-sys-color-error-container': '#8c1d18',
  '--md-sys-color-inverse-on-surface': '#322f35',
  '--md-sys-color-inverse-primary': '#6750a4',
  '--md-sys-color-inverse-surface': '#e6e0e9',
  '--md-sys-color-on-background': '#e6e0e9',
  '--md-sys-color-on-error': '#601410',
  '--md-sys-color-on-error-container': '#f9dedc',
  '--md-sys-color-on-primary': '#381e72',
  '--md-sys-color-on-primary-container': '#eaddff',
  '--md-sys-color-on-primary-fixed': '#21005d',
  '--md-sys-color-on-primary-fixed-variant': '#4f378b',
  '--md-sys-color-on-secondary': '#332d41',
  '--md-sys-color-on-secondary-container': '#e8def8',
  '--md-sys-color-on-secondary-fixed': '#1d192b',
  '--md-sys-color-on-secondary-fixed-variant': '#4a4458',
  '--md-sys-color-on-surface': '#e6e0e9',
  '--md-sys-color-on-surface-variant': '#cac4d0',
  '--md-sys-color-on-tertiary': '#492532',
  '--md-sys-color-on-tertiary-container': '#ffd8e4',
  '--md-sys-color-on-tertiary-fixed': '#31111d',
  '--md-sys-color-on-tertiary-fixed-variant': '#633b48',
  '--md-sys-color-outline': '#938f99',
  '--md-sys-color-outline-variant': '#49454f',
  '--md-sys-color-primary': '#d0bcff',
  '--md-sys-color-primary-container': '#4f378b',
  '--md-sys-color-primary-fixed': '#eaddff',
  '--md-sys-color-primary-fixed-dim': '#d0bcff',
  '--md-sys-color-scrim': '#000',
  '--md-sys-color-secondary': '#ccc2dc',
  '--md-sys-color-secondary-container': '#4a4458',
  '--md-sys-color-secondary-fixed': '#e8def8',
  '--md-sys-color-secondary-fixed-dim': '#ccc2dc',
  '--md-sys-color-shadow': '#000',
  '--md-sys-color-surface': '#141218',
  '--md-sys-color-surface-bright': '#3b383e',
  '--md-sys-color-surface-container': '#211f26',
  '--md-sys-color-surface-container-high': '#2b2930',
  '--md-sys-color-surface-container-highest': '#36343b',
  '--md-sys-color-surface-container-low': '#1d1b20',
  '--md-sys-color-surface-container-lowest': '#0f0d13',
  '--md-sys-color-surface-dim': '#141218',
  '--md-sys-color-surface-tint': '#d0bcff',
  '--md-sys-color-surface-variant': '#49454f',
  '--md-sys-color-tertiary': '#efb8c8',
  '--md-sys-color-tertiary-container': '#633b48',
  '--md-sys-color-tertiary-fixed': '#ffd8e4',
  '--md-sys-color-tertiary-fixed-dim': '#efb8c8',
  '--md-ref-typeface-brand': 'Roboto',
  '--md-ref-typeface-plain': 'Roboto',
  '--md-ref-typeface-weight-bold': '700',
  '--md-ref-typeface-weight-medium': '500',
  '--md-ref-typeface-weight-regular': '400',
  '--md-sys-typescale-display-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-large-line-height': '4rem',
  '--md-sys-typescale-display-large-size': '3.5625rem',
  '--md-sys-typescale-display-large-weight': '400',
  '--md-sys-typescale-display-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-medium-line-height': '3.25rem',
  '--md-sys-typescale-display-medium-size': '2.8125rem',
  '--md-sys-typescale-display-medium-weight': '400',
  '--md-sys-typescale-display-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-display-small-line-height': '2.75rem',
  '--md-sys-typescale-display-small-size': '2.25rem',
  '--md-sys-typescale-display-small-weight': '400',
  '--md-sys-typescale-headline-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-large-line-height': '2.5rem',
  '--md-sys-typescale-headline-large-size': '2rem',
  '--md-sys-typescale-headline-large-weight': '400',
  '--md-sys-typescale-headline-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-medium-line-height': '2.25rem',
  '--md-sys-typescale-headline-medium-size': '1.75rem',
  '--md-sys-typescale-headline-medium-weight': '400',
  '--md-sys-typescale-headline-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-headline-small-line-height': '2rem',
  '--md-sys-typescale-headline-small-size': '1.5rem',
  '--md-sys-typescale-headline-small-weight': '400',
  '--md-sys-typescale-title-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-large-line-height': '1.75rem',
  '--md-sys-typescale-title-large-size': '1.375rem',
  '--md-sys-typescale-title-large-weight': '400',
  '--md-sys-typescale-title-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-medium-line-height': '1.5rem',
  '--md-sys-typescale-title-medium-size': '1rem',
  '--md-sys-typescale-title-medium-weight': '500',
  '--md-sys-typescale-title-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-title-small-line-height': '1.25rem',
  '--md-sys-typescale-title-small-size': '0.875rem',
  '--md-sys-typescale-title-small-weight': '500',
  '--md-sys-typescale-body-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-large-line-height': '1.5rem',
  '--md-sys-typescale-body-large-size': '1rem',
  '--md-sys-typescale-body-large-weight': '400',
  '--md-sys-typescale-body-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-medium-line-height': '1.25rem',
  '--md-sys-typescale-body-medium-size': '0.875rem',
  '--md-sys-typescale-body-medium-weight': '400',
  '--md-sys-typescale-body-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-body-small-line-height': '1rem',
  '--md-sys-typescale-body-small-size': '0.75rem',
  '--md-sys-typescale-body-small-weight': '400',
  '--md-sys-typescale-label-large-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-large-line-height': '1.25rem',
  '--md-sys-typescale-label-large-size': '0.875rem',
  '--md-sys-typescale-label-large-weight': '500',
  '--md-sys-typescale-label-medium-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-medium-line-height': '1rem',
  '--md-sys-typescale-label-medium-size': '0.75rem',
  '--md-sys-typescale-label-medium-weight': '500',
  '--md-sys-typescale-label-small-font': 'var(--md-ref-typeface-plain)',
  '--md-sys-typescale-label-small-line-height': '1rem',
  '--md-sys-typescale-label-small-size': '0.6875rem',
  '--md-sys-typescale-label-small-weight': '500',
  '--md-sys-typescale-label-large-weight-prominent': '700',
  '--md-sys-typescale-label-medium-weight-prominent': '700',
  '--md-sys-shape-corner-extra-large': '28px',
  '--md-sys-shape-corner-extra-small': '4px',
  '--md-sys-shape-corner-full': '9999px',
  '--md-sys-shape-corner-large': '16px',
  '--md-sys-shape-corner-medium': '12px',
  '--md-sys-shape-corner-none': '0px',
  '--md-sys-shape-corner-small': '8px',
  '--md-divider-color': 'var(--md-sys-color-outline-variant)',
  '--md-divider-thickness': '1px',
  '--md-badge-color': 'var(--md-sys-color-error)',
  '--md-badge-large-color': 'var(--md-sys-color-error)',
  '--md-badge-large-label-text-color': 'var(--md-sys-color-on-error)',
  '--md-badge-large-label-text-font':
    'var(--md-sys-typescale-label-small-font)',
  '--md-badge-large-label-text-line-height':
    'var(--md-sys-typescale-label-small-line-height)',
  '--md-badge-large-label-text-size':
    'var(--md-sys-typescale-label-small-size)',
  '--md-badge-large-label-text-weight':
    'var(--md-sys-typescale-label-small-weight)',
  '--md-badge-large-shape': 'var(--md-sys-shape-corner-full)',
  '--md-badge-large-size': '16px',
  '--md-badge-shape': 'var(--md-sys-shape-corner-full)',
  '--md-badge-size': '6px',
} as const;
